### ISSUE TITLE
How to test in KITTI dataset？

### ISSUE THREAD

**Issue by freshwk** [TuSimple/LiDAR_RCNN#18]
Thank you for your great work！
I am quite interested in your work.I want to know how to run the code in KITTI dataset,it seems that the code you released doesn't support KITTI.Looking forward to your reply.

**Comment by Lzc6996** [comment]
@wangkai602058765 
In our paper's Table 3, we show the KITTI results. But we don't recommend do experiments on KITTI datasets becasue amount of data is too small. LiDAR R-CNN works by fitting the residuals upon first-stage models, however, without enough data, the model will be very sensitive to parameters, augmentations or tricks. That's why we focus on Waymo Open Datasets.

**Comment by freshwk** [comment]
> @wangkai602058765
> In our paper's Table 3, we show the KITTI results. But we don't recommend do experiments on KITTI datasets becasue amount of data is too small. LiDAR R-CNN works by fitting the residuals upon first-stage models, however, without enough data, the model will be very sensitive to parameters, augmentations or tricks. That's why we focus on Waymo Open Datasets.

Thank you for your reply！
