### ISSUE TITLE
Question about virtual points

### ISSUE THREAD

**Issue by mrqrs** [TuSimple/LiDAR_RCNN#25]
Thanks for your nice work!
The paper shows the different pooling method. To add virtual points in the proposal box is well for model result. But I can not find the about code in your project. 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/26370029/131260706-ad59e9a2-b2f3-41ad-9a6c-416b50a54c0f.png">
Can you tell me where the code about 'virtual points', waiting for your replay. 
Thanks.

**Comment by Lzc6996** [comment]
@mrqrs 
Thanks for interesting.
In our paper, we propose some methonds to handle the "Size Ambiguity Problem", and we use the ["Boundary offset"](https://github.com/TuSimple/LiDAR_RCNN/blob/89c5fefd46563c15f31b8cda76e7ab09e2ddca0d/src/LiDAR_RCNN/datasets/waymo/data_utils.py#L33-L36) instead of "virtual points" in this public code. Actually, the two methods achieve similar results.

**Comment by mrqrs** [comment]
Thanks for your reply.
